---
- name: Setup Runit repo
  become: true
  yum_repository:
    baseurl: "{{ runit_yum_baseurl }}"
    description: Runit
    gpgkey: "{{ runit_yum_gpgkey }}"
    gpgcheck: "{{ runit_repo_gpg_check  }}"
    name: Runit
    sslverify: "{{ runit_yum_sslverify }}"
  when:
    - runit_manage_repo

- name: Install Runit
  become: true
  package:
    name: runit
    state: installed

- name: Create service definition directory
  become: true
  file:
    group: root
    mode: "u=wrx,go="
    owner: root
    path: /etc/sv
    state: directory

- name: Create default Runit directory
  become: true
  file:
    path: /etc/service
    state: directory
    owner: root
    group: root
    mode: "u=wrx,go=rx"

- name: Link the Ansible default runit directory to the one that our Runit uses
  become: true
  file:
    dest: /var/service
    src: /etc/service
    state: link

- name: Ensure runsvdir is really running (avoid msg unable to open supervise/ok)
  become: true
  shell: ps -ef |  grep runsvdir | grep -v grep
  register: process_runsvdir
  changed_when: false
  ignore_errors: true


- block: 
  - name: Kill all unsupervised runsv processes
    become: true
    shell: killall runsv
    changed_when: false
    ignore_errors: true

  - name: Start "runsvdir" if needed
    become: true
    shell: "cd /tmp; nohup runsvdir -P -H /etc/service log: ........................................................................................................................................................................................................................................................................................................................................................................................................... </dev/null >/dev/null 2>&1 &"
    async: 2592000  # 60*60*24*30 – 1 month
    poll: 0
  when: "process_runsvdir.stdout.find('runsvdir') == -1"
